### PR TITLE
refactor config parameters

### PR DESCRIPTION
**Pull request by younesdiouri**
Hello,
I've updated your files with a new architecture  : 
 
### Core directory  
You can find here your global settings and database settings. 
It is helpful to use such a file because each time you'll update your database name / user etc. you won't have to rename it in all your project files. 

### Database files
I also added mysqli instead of deprecated mysqlconnect. You can use your mysqli object from any file using `require_once' '` method. 

###Next step?
Maybe we can try to comply with PSR-4, as using autoloader ...

### CODE REVIEW

**Review by shauryauppal — CHANGES_REQUESTED** [review]
Your PR changed the entire repo.

Mysqli you are using, password you are setting myPassword

This is a guide repo which will help beginners. Those connectivity line where written on purpose so that newbie is not confused. I completely understand you made a PR as per standards of real PHP programming but for a beginner don't you thing these changes will confuse him/her.

**Comment by shauryauppal** [comment]
Your efforts and time spend on this is appreciated.

**Comment by shauryauppal** [comment]
Maybe your method of configuration can be added in a separate folder that tells this is another way of configuration. @younesdiouri

**Comment by younesdiouri** [comment]
Thank you for your feedback. Indeed this can be a second step for a beginner. I will reroll it with all this content in a separate folder.

**Review by younesdiouri — COMMENTED** [review]
Hello back (sorry worked alot these days) , I've separated my changes into a folder, and kept your last version of files into it. Hope it's not messy. 
Thank you again for your last feedback. 
Have a good weekend

**Comment by shauryauppal** [comment]
@younesdiouri but your changes to the main files still exist. You should have reset through git and then made your folder changes.

**Comment by shauryauppal** [comment]
@younesdiouri check the section files changed once.

**Comment by younesdiouri** [comment]
@shauryauppal you are right, I'll just redo a PR then?

**Comment by shauryauppal** [comment]
You can check on stackoverflow how to drop a commit. git rebase -i HEAD~n can help you in this.

**Comment by shauryauppal** [comment]
@younesdiouri You just need to remove your previous commits in PR. If you are unable to make it you may make a new PR, I will close this one and merge that PR.

**Review by younesdiouri — COMMENTED** [review]
Here I deleted all the useless commits. Could you check if this one fits ? Again thank you for your help

**Comment by shauryauppal** [comment]
@younesdiouri Great work merging, but please add a README fill in your new FOLDER also how would someone understand.

**Comment by shauryauppal** [comment]
@younesdiouri Explain what new You did how is it different than the first method.

**Pull request merged**
